export const CHANGE_LIGHT = "change light";
export const GET_ALL_NEWS = "get all new";
export const GET_FAIL = "get fail";
export const GET_SUCCES = "get succes";
export const GET_INFO_NEWS = "get info news";
export const GET_SUCCES_INFO = "get success info";
export const CHANGE_CHOOSE_TOPIC = "change choose topic";
export const GET_DATA_FROM_REALM = "get_data_from_realm";
export const GET_DATA_FROM_REALM_SAVED = "get_data_from_realm_saved";
export const GET_DATA_FROM_REALM_FAVORITE = "get_data_from_realm_favorite";
export const SEARCH = "search"